---
title: "In-class Exercise 2"
author: "Santhya Selvan"
date: "August 26, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  freeze: true
---

## Getting Started

First and foremost, we will load the needed packages into our Rstudio using pacman's `p_load` function.

```{r}
pacman::p_load(sf, tidyverse)
```

We can now load our data into our R environment as new data frames.

```{r}
mpsz14_shp <- st_read(dsn="data3", layer="MP14_SUBZONE_WEB_PL")
```

checking to make sure that th

```{r}
class(mpsz14_shp)
```

```{r}
#| output: false
st_write(mpsz14_shp, "data3/MP14_SUBZONE_WEB_PL.kml", delete_dsn=TRUE)
```

changing the crs of the data files

```{r}
mpsz19_kml = st_read ("data3/MasterPlan2019SubzoneBoundaryNoSeaKML.kml") %>% 
  st_transform(crs=3414)
```

```{r}
mpsz19_shp = st_read(dsn = "data3/", layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
```

checking the crs of the data files

```{r}
st_crs(mpsz19_shp)
```

```{r}
st_crs(mpsz19_kml)
```

```{r}
popdata323 <- read_csv("data3/respopagesextod2023.csv") 
```

```{r}
popdata3_2023 <- read_csv("data3/respopagesextod2023.csv") %>% 
  group_by(PA, SZ, AG) %>% 
  summarise('POP'= sum(`Pop`)) %>% 
  ungroup() %>% 
  pivot_wider(names_from=AG, 
              values_from=POP)

```

```{r}
popdata3_2023 <- popdata3_2023 %>%
  mutate_at(.vars = vars(PA, SZ), 
          .funs = list(toupper))
```

```{r}
mpsz_pop2020 <- left_join(popdata3_2023, mpsz19_shp,
                          by = c("SZ" = "SUBZONE_N"))
```
